theme: minima
title: Github Page
author: DFLBB
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the first awesome page made with Github Pages.

# social links
twitter_username: my-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  DFLBB # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
